version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/ami
    steps:
      - checkout
      - run:
          name: Validate 
          command: packer validate ubuntu-ami.json

  packer-build:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Packer Build
          command: packer build -var 'aws_access_key=${aws_access_key}' -var 'aws_secret_key=${aws_secret_key}' -var 'aws_region=${aws_region}' -var 'aws_source_ami=${aws_source_ami}' ubuntu-ami.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - packer-build:
          requires:
            - validate
          filters:
            branches:
              only: master