version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/ami
    steps:
      - checkout
      - run:
          name: Validate 
          command: packer validate ubuntu-ami.json

  packer-build:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Packer Build
          command: packer build ubuntu-ami.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - packer-build:
          requires:
            - validate
          filters:
            branches:
              only: master